### ISSUE TITLE
Step 5 - IAM least privileges for Kinesis Firehose

### ISSUE THREAD

**Issue by alexcasalboni** [aws-samples/aws-serverless-workshop-innovator-island#45]
The simular app includes this policy:

```yaml
- Statement:
    - Effect: Allow
       Resource: '*'
       Action:
          - firehose:PutRecordBatch
```

Since we've just created the Kinesis Firehose Delivery Stream, it'd be pretty straightforward to show customers how to update this policy with the Delivery Stream ID (instead of `Resource: '*'`), using the `StreamName` CloudFormation parameter.

Or we could at least limit the policy to that specific stream name in all regions:

```yaml
Resource: !Sub arn:aws:firehose:*:*:deliverystream/${StreamName}
```
